### ISSUE TITLE
Sending a MultipartPayload always does a POST

### ISSUE THREAD

**Issue by kevinrenskers** [MihaelIsaev/CodyFire#11]
It's currently not possible to send a MultipartPayload request via PUT or PATCH, it always [overrides it](https://github.com/MihaelIsaev/CodyFire/blob/master/CodyFire/Classes/APIRequest+SendMultipart.swift#L66) to a POST request. Is this expected, or a bug?

**Comment by MihaelIsaev** [comment]
It's definitely a bug! I've just fixed it in `v.1.11.1`, thanks!

**Comment by kevinrenskers** [comment]
Great, thanks! Looking forward to a new version on Cocoapods :)

**Comment by MihaelIsaev** [comment]
@kevinrenskers yeah, just uploaded it, you could update now 🙂

**Comment by kevinrenskers** [comment]
Hm I updated to 1.11.1, but it's still sending my request via POST.

```
func updateUser(_ payload: EditUserData) -> APIRequest<User> {
  return APIRequest("user/", payload: serverPayload).method(.put)
}
```

(where EditUserData is a MultipartPayload struct)


```
🌸 [CodyFire]: PUT to http://minotaur.local:8000/api/user/
🌸 [CodyFire]: Response: 405 on PUT to http://minotaur.local:8000/api/user/
🌸 [CodyFire]: Error: PUT user/ methodNotAllowed

status: methodNotAllowed
method: put
endpoint: user/
headers: ["Authorization": "Bearer xyz"]
httpBody:{"detail":"Method \"POST\" not allowed."}
json: ["detail": Method "POST" not allowed.]
```

So the logs seem to indicate that it thinks it's sending via PUT, but the actual http method is actually a POST. Confirmed via Charles proxy.

**Comment by kevinrenskers** [comment]
Never mind, clean build solves the problem :)
