### ISSUE TITLE
Can't compile 1.12.0

### ISSUE THREAD

**Issue by cipi1965** [MihaelIsaev/CodyFire#13]
It's impossible to compile 1.12.0 version because `PrimitiveTypeDecoder.swift` isn't in `CodyFire/Classes`, could you please create a new version tag?

**Comment by MihaelIsaev** [comment]
Wow, let me check

**Comment by cipi1965** [comment]
Thank you

**Comment by cipi1965** [comment]
You fixed it in `2c30fa9fec33a5a2963879eccaee4ec6343c278a` commit

**Comment by MihaelIsaev** [comment]
First of all thank you for letting me know about this issue ❤️

I've pushed `1.13.0` tag here and to Cocoapods as well 🙂 

<img width="392" alt="Screenshot 2020-03-17 at 00 09 03" src="https://user-images.githubusercontent.com/1272610/76795808-897b0780-67e3-11ea-854c-82d6ea3032cc.png">

**Comment by cipi1965** [comment]
Thank you very much :)
