### ISSUE TITLE
Unable to find a specification for `CodyFire`

### ISSUE THREAD

**Issue by SergeyDevUA** [MihaelIsaev/CodyFire#2]
pod 'CodyFire'

Hello, I try pod install, but it still:
[!] Unable to find a specification for `CodyFire`

pod search CodyFire
[!] Unable to find a pod with name, author, summary, or description matching `CodyFire`

Does it means still indexing?

**Comment by MihaelIsaev** [comment]
Hey @SergeyDevUA 
Looks like a problem with your pod master repo because [CodyFire is available on cocoapods.org](https://cocoapods.org/pods/CodyFire)
Take a look at [this answer](https://stackoverflow.com/a/32850706/1001057) on stackoverflow it should resolve the problem.
